title: Zahidul Hossain
description: > # this means to ignore newlines until "baseurl:"
  স্বপ্নীল চোখে স্বপ্নালু হয়ে দিচ্ছি পাড়ি বিদ্ধস্ত জনপদ
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "choyan.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: ch0yan#if your site has a twitter account, enter it here

# Author Settings
author: Zahidul Hossain # add your name
author-img: choyan.img # add your photo
about-author: I am a web developer focusing on front-end development. Always hungry to keep learning. # add description
twitter: ch0yan# add your Twitter handle
facebook: # add your Facebook handle
github: choyan # add your Github handle
linkedin: choyan# add your Linkedin handle
email: choyan.009@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude:
  - Gemfile
  - Gemfile.lock
